package com.hmily.common;

public enum  YoutuResponseCodeConstant {
    OK(0, "OK", "请求成功"),

    SDK_DISTANCE_ERROR(-1100, "SDK_DISTANCE_ERROR", "相似度错误"),
    SDK_IMAGE_FACEDETECT_FAILED(-1101, "SDK_IMAGE_FACEDETECT_FAILED", "人脸检测失败 "),
    SDK_IMAGE_DECODE_FAILED(-1102, "SDK_IMAGE_DECODE_FAILED", "图片解码失败"),
    SDK_FEAT_PROCESSFAILED(-1103, "SDK_FEAT_PROCESSFAILED", "特征处理失败 "),
    SDK_FACE_SHAPE_FAILED(-1104, "SDK_FACE_SHAPE_FAILED", "提取轮廓错误"),
    SDK_FACE_GENDER_FAILED(-1105, "SDK_FACE_GENDER_FAILED", "提取性别错误 "),
    SDK_FACE_EXPRESSION_FAILED(-1106, "SDK_FACE_EXPRESSION_FAILED", "提取表情错误"),
    SDK_FACE_AGE_FAILED(-1107, "SDK_FACE_AGE_FAILED", "提取年龄错误 "),
    SDK_FACE_POSE_FAILED(-1108, "SDK_FACE_POSE_FAILED", "提取姿态错误"),
    SDK_FACE_GLASS_FAILED(-1109, "SDK_FACE_GLASS_FAILED", "提取眼镜错误"),
    SDK_FACE_BEAUTY_FAILED(-1110, "SDK_FACE_BEAUTY_FAILED", "提取魅力值错误"),
    TTS_PROCESS_FAILED(-1001, "TTS_PROCESS_FAILED", "语音合成失败 "),

    STORAGE_ERROR(-1200, "STORAGE_ERROR", "存储错误"),
    CACHE_ERROR(-1201, "CACHE_ERROR", "缓存错误 "),

    ERROR_IMAGE_EMPTY(-1300, "ERROR_IMAGE_EMPTY", "图片为空"),
    ERROR_PARAMETER_EMPTY(-1301, "ERROR_PARAMETER_EMPTY", "参数为空"),
    ERROR_PERSON_EXISTED(-1302, "ERROR_PERSON_EXISTED", "个体已存在"),
    ERROR_PERSON_NOT_EXISTED(-1303, "ERROR_PERSON_NOT_EXISTED", "个体不存在"),
    ERROR_PARAMETER_TOO_LONG(-1304, "ERROR_PARAMETER_TOO_LONG", "参数过长"),
    ERROR_FACE_NOT_EXISTED(-1305, "ERROR_FACE_NOT_EXISTED", "人脸不存在"),
    ERROR_GROUP_NOT_EXISTED(-1306, "ERROR_GROUP_NOT_EXISTED", "组不存在"),
    ERROR_GROUPLIST_NOT_EXISTED(-1307, "ERROR_GROUPLIST_NOT_EXISTED", "组列表不存在"),
    ERROR_DOWNLOAD_IMAGE_FAILED(-1308, "ERROR_DOWNLOAD_IMAGE_FAILED", "url图片下载失败"),
    ERROR_FACE_NUM_EXCEED(-1309, "ERROR_FACE_NUM_EXCEED", "人脸个数超过限制"),
    ERROR_PERSON_NUM_EXCEED(-1310, "ERROR_PERSON_NUM_EXCEED", "个体个数超过限制"),
    ERROR_GROUP_NUM_EXCEED(-1311, "ERROR_GROUP_NUM_EXCEED", "组个数超过限制"),
    ERROR_SAME_FACE_ADDED(-1312, "ERROR_SAME_FACE_ADDED", "对个体添加了几乎相同的人脸"),
    ERROR_PARAMETER_INVALID(-1313, "ERROR_PARAMETER_INVALID", "参数不合法（特殊字符比如空格、斜线、tab、换行符）"),
    ERROR_IMAGE_FORMAT_INVALID(-1400, "ERROR_IMAGE_FORMAT_INVALID", "无效的图片格式"),
    ERROR_IMAGE_FUZZY_DETECT_FAILED(-1401, "ERROR_IMAGE_FUZZY_DETECT_FAILED", "图片模糊度检测失败"),
    ERROR_IMAGE_FOOD_DETECT_FAILED(-1402, "ERROR_IMAGE_FOOD_DETECT_FAILED", "美食图片检测失败"),
    ERROR_IMAGE_DOWNLOAD_FAILED(-1403, "ERROR_IMAGE_DOWNLOAD_FAILED", "图片下载失败"),
    ERROR_IMAGE_CLASSIFY_FAILED(-1404, "ERROR_IMAGE_CLASSIFY_FAILED", "算法模型调用错误"),
    ERROR_IMAGE_FINGERPRINT_FAILED(-1405, "ERROR_IMAGE_FINGERPRINT_FAILED", "提取图像指纹失败"),
    ERROR_IMAGE_COMPARE_FAILED(-1406, "ERROR_IMAGE_COMPARE_FAILED", "美食图片检测失败"),
    ERROR_DOWNLOAD_IMAGE_SIZE_EXCEED(-1408, "ERROR_IMAGE_FOOD_DETECT_FAILED", "图片超出下载限制"),
    ERROR_IMAGE_UNSATISFACTORY(-1409, "ERROR_IMAGE_FOOD_DETECT_FAILED", "图片不满足检测要求"),

    ERROR_IVADLID_URL_FROMAT(-1505, "ERROR_IVADLID_URL_FROMAT", "图像请求URL的格式错误"),
    ERROR_DOWNLOAD_TIMEOUT(-1506, "ERROR_DOWNLOAD_TIMEOUT", "图像下载超时"),
    ERROR_CONNECT_DOWNLOAD_SERVER(-1507, "ERROR_CONNECT_DOWNLOAD_SERVER", "无法连接图像下载服务器"),

    TEXT_EMPTY(-2000, "ERROR_IMAGE_FOOD_DETECT_FAILED", "文本为空"),
    TEXT_TOO_LONG(-2001, "TEXT_TOO_LONG", "文本过长"),

    OCR_BUF_EMPTY(-5101, "OCR_BUF_EMPTY", "OCR照片为空"),
    OCR_RECOG_FAILED(-5103, "OCR_RECOG_FAILED", "OCR识别失败"),
    OCR_CORNER_INCOMPLETE(-5106, "OCR_CORNER_INCOMPLETE", "身份证边框不完整"),
    OCR_NOT_IDCARD(-5107, "OCR_NOT_IDCARD", "输入图片不是身份证"),
    OCR_IDCARD_ILLEGAL(-5108, "OCR_IDCARD_ILLEGAL", "身份证信息不合规范"),
    OCR_IMAGE_BLUR(-5109, "OCR_IMAGE_BLUR", "照片模糊"),

    OCR_NOT_ENOUGH_TEXTLINES(-5201, "OCR_NOT_ENOUGH_TEXTLINES", "名片无足够文本"),
    OCR_TEXTLINES_SKEWED(-5202, "OCR_TEXTLINES_SKEWED", "名片文本行倾斜角度太大"),
    OCR_TEXTLINES_FUZZY(-5203, "OCR_TEXTLINES_FUZZY", "名片模糊"),
    OCR_UNRECOG_NAME(-5204, "OCR_UNRECOG_NAME", "名片姓名识别失败"),
    OCR_UNRECOG_TEL(-5205, "OCR_UNRECOG_TEL", "名片电话识别失败"),
    OCR_NOT_A_NAMECARD(-5206, "OCR_NOT_A_NAMECARD", "图像为非名片图像"),
    DETECT_AND_RECONG_FAILED(-5207, "DETECT_AND_RECONG_FAILED", "检测或者识别失败"),
    OCR_SERVER_INTERN_ERROR(-5208, "OCR_SERVER_INTERN_ERROR", "服务内部错误"),

    NOT_CARD(-7001, "NOT_CARD", "未检测到身份证，请对准边框(请避免拍摄时倾角和旋转角过大、摄像头)"),
    NOT_SECOND_IDCARD(-7002, "NOT_SECOND_IDCARD", "请使用第二代身份证件进行扫描"),
    NOT_FRONT_IDCARD(-7003, "NOT_FRONT_IDCARD", "不是身份证正面照片(请使用带证件照的一面进行扫描)"),
    NOT_BACK_IDCARD(-7004, "NOT_BACK_IDCARD", "不是身份证反面照片(请使用身份证反面进行扫描)"),
    IDCARD_FUZZY(-7005, "IDCARD_FUZZY", "确保扫描证件图像清晰"),
    IDCARD_LIGHT_NOT_BLANCE(-7006, "IDCARD_LIGHT_NOT_BLANCE", "请避开灯光直射在证件表面"),

    DLOCR_WRONG_TYPE_INPUT(-9001, "DLOCR_WRONG_TYPE_INPUT", "请求type错误，不是0，1"),
    DLOCR_RECONG_FAILED(-9002, "DLOCR_RECONG_FAILED", "OCR识别失败"),
    GLOCR_RECONG_FAILED(-9003, "GLOCR_RECONG_FAILED", "OCR识别失败"),

    CREDITCARD_OCR_PREPROCESS_ERROR(-9010, "CREDITCARD_OCR_PREPROCESS_ERROR", "银行卡OCR预处理错误"),
    CREDITCARD_OCR_RECOG_FAILED(-9011, "CREDITCARD_OCR_RECOG_FAILED", "OCR识别失败"),
    CREDITCARD_OCR_IMAGE_BLUR(-9012, "CREDITCARD_OCR_IMAGE_BLUR", "银行卡图片模糊"),
    ERROR_NOT_A_CREDITCARD(-9013, "ERROR_NOT_A_CREDITCARD", "不是银行卡"),
    ERROR_CREDITCARD_ILLEGAL(-9014, "ERROR_CREDITCARD_ILLEGAL", "卡号为空或不符合规范"),
    JAPOCR_RECONG_FAILED(-9016, "JAPOCR_RECONG_FAILED", "OCR识别失败"),

    HANDAR_NO_HANDS(-9101, "HANDAR_NO_HANDS", "检测不到手"),
    HANDAR_HAND_CLS_FAILED(-9102, "HANDAR_HAND_CLS_FAILED", "分类失败"),

    BIZLICENSE_OCR_PREPROCESS_FAILED(-9501, "BIZLICENSE_OCR_PREPROCESS_FAILED", "营业执照OCR"),
    BIZLICENSE_OCR_RECOG_FAILED(-9502, "BIZLICENSE_OCR_RECOG_FAILED", "营业执照OCR"),

    PLATE_OCR_PREPROCESS_ERROR(-9701, "PLATE_OCR_PREPROCESS_ERROR", "车牌OCR预处理错误"),
    PLATE_OCR_RECOG_FAILED(-9702, "PLATE_OCR_RECOG_FAILED", "车牌OCR识别失败");

    private final int errorcode;
    private final String errormsg;
    private final String errorZhMsg;


    private YoutuResponseCodeConstant(int errorcode, String errormsg, String errorZhMsg) {
        this.errorcode = errorcode;
        this.errormsg = errormsg;
        this.errorZhMsg = errorZhMsg;
    }


    public int getErrorcode() {
        return errorcode;
    }


    public String getErrormsg() {
        return errormsg;
    }


    public String getErrorZhMsg() {
        return errorZhMsg;
    }






}

